export const projectData = [
    {
        projHeader: 'Content_Rediscovery.txt',
        title: 'C-Sphere',
        time: 'May 2025',
        imgPath: 'csphere-home-1.png',
        ghUrl: 'https://github.com/Claudio-Perinuzzi/Csphere',
        demoUrl: false,
        description: [
            { text: 'Collaborated with a ', highlight: false },
            { text: 'team of 3 ', highlight: true },
            { text: 'to build a full-stack web app that ', highlight: false },
            { text: 'intelligently summarizes, organizes ', highlight: true },
            { text: 'and helps users rediscover saved bookmarks through advanced search capabilities.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },            
            { text: 'Engineered a ', highlight: false },
            { text: 'Retrieval-Augmented Generation (RAG) ', highlight: true },
            { text: 'backend pipeline by combining ', highlight: false },
            { text: 'intelligent content summarization, semantic vector search, and embedding-based storage/retrieval using PostgreSQL, ', highlight: true },
            { text: 'resulting in optimized user data storage and intelligent content querying.', highlight: false },
        ]
    },    
    {
        projHeader: 'Learn_American_Sign_Language.txt',
        title: 'Gesture Once',
        time: 'December 2024',
        imgPath: 'asl_demo.gif',
        ghUrl: 'https://github.com/Claudio-Perinuzzi/Gesture-Once',
        demoUrl: false,
        description: [
            { text: 'Collaborated with a ', highlight: false },
            { text: 'team of 3 ', highlight: true },
            { text: 'to train and fine-tune an Ultralytics YOLO object detection model for recognizing and classifying ASL (American Sign Language) gestures, ', highlight: false },
            { text: 'achieving a precision of 97.8%.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Built the backend in ', highlight: false },
            { text: 'Python, ', highlight: true },
            { text: 'leveraging ', highlight: false },
            { text: 'Roboflow for data preprocessing and augmentation, ', highlight: true },
            { text: 'and contributed to building a ', highlight: false },
            { text: 'React-based frontend in JavaScript.', highlight: true },
        ]
    },
    {
        projHeader: 'NYC_AQI_Predictor.txt',
        title: 'Breathe NYC',
        time: 'September 2024',
        imgPath: 'aqi_img.png',
        ghUrl: 'https://github.com/Claudio-Perinuzzi/nyc-air-quality-heat-map-predictor',
        demoUrl: "https://nyc-aqi-predictor.streamlit.app/",
        description: [
            { text: 'Developed a ', highlight: false },
            { text: 'Python web app with Streamlit using NYC OpenData ', highlight: true },
            { text: 'public datasets to visualize, analyze, and predict yearly and seasonal AQI (Air Quality Index) trends for NYC neighborhoods, ', highlight: false },
            { text: 'achieving 97% accuracy.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Leveraged ', highlight: false },
            { text: 'pandas and scikit-learn to build a data cleaning and linear regression machine learning pipeline, ', highlight: true },
            { text: 'delivering actionable insights from ', highlight: false },
            { text: 'raw data ', highlight: true },
            { text: 'via an intuitive interface for ', highlight: false },
            { text: 'critical decision support.', highlight: true },
        ]
    },
    {
        projHeader: 'Social_Media_Addiction_Predictor.txt',
        title: 'MindfulNet AI',
        time: 'May 2024',
        imgPath: 'smup_img.png',
        ghUrl: 'https://github.com/Claudio-Perinuzzi/MindfulNet-AI',
        demoUrl: "https://claudio-perinuzzi.github.io/MindfulNet-AI/",
        description: [
            { text: "Implemented a ", highlight: false },
            { text: "full stack web application using React ", highlight: true },
            { text: "that predicts social media addiction with ", highlight: false },
            { text: "98% accuracy ", highlight: true },
            { text: "and offers personalized healthy habit recommendations based on user interests and location.", highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Built a ', highlight: false },
            { text: 'backend Random Forest machine learning model in Java ', highlight: true },
            { text: 'to predict social media addiction given user-provided information, including social media habits and socioeconomic background.', highlight: false },
        ]
    },
    {
        projHeader: 'PDF_Encrypt.txt',
        title: 'PDF Encrypt',
        time: 'July 2023',
        imgPath: 'pdf_encrypt.png',
        ghUrl: 'https://github.com/Claudio-Perinuzzi/encrypt-pdf',
        demoUrl: false,
        description: [
            { text: "Developed a  ", highlight: false },
            { text: "Python-based ", highlight: true },
            { text: "Graphical User Interface (GUI) to ", highlight: false },
            { text: "efficiently encrypt multiple PDFs simultaneously, ", highlight: true },
            { text: "allowing users to ", highlight: false },
            { text: "save time by securely encrypting files in bulk.", highlight: true }
        ]
    }
];
