export const experienceData = [
    {
        fileName: 'East_End_Hand_Surgery.txt',
        title: 'Software Developer/Data Manager',
        time: 'May 2016 - Present',
        description: [
            { text: 'Develop custom ', highlight: false },
            { text: 'Python software applications to integrate with EMR systems, ', highlight: true },
            { text: 'automating clinical workflow tasks such as patient directory creation, email generation, and batch file encryption, saving clinical staff ', highlight: false },
            { text: '8+ hours each week.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Manage and organize ', highlight: false },
            { text: '2+ TB ', highlight: true },
            { text: 'of sensitive patient records, ensuring ', highlight: false },
            { text: 'data integrity and security ', highlight: true },
            { text: 'of backups.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: "Led the successful reorganization of the company's file structure, significantly improving data retrieval and storage efficiency by", highlight: false },
            { text: ' 2x and directly contributing to increased clinical productivity.', highlight: true },
        ]
    },
    {
        fileName: 'Data_Annotation_Tech.txt',
        title: 'ML Specialist - LLM Training & Debugging',
        time: 'April 2024 - Present',
        description: [
            { text: 'Apply', highlight: false },
            { text: ' Reinforcement Learning from Human Feedback (RLHF)', highlight: true },
            { text: ' to enhance the', highlight: false },
            { text: ' efficiency and adaptability', highlight: true },
            { text: ' of machine learning models.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Debug and optimize code', highlight: true },
            { text: ' ensuring compliance with ethical and legal standards in ', highlight: false },
            { text: ' data-sensitive environments.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },            
            { text: 'Leverage', highlight: false },
            { text: ' prompt engineering techniques', highlight: true },
            { text: ' to evaluate and improve model performance.', highlight: false },
        ]
    },    
    {
        fileName: 'CUNY_Tech_Prep.txt',
        title: 'Data Science & Software Engineer Fellow',
        time: 'July 2024 - May 2025',
        description: [
            { text: 'Accepted into a ', highlight: false },
            { text: 'highly competitive year-long data science fellowship ', highlight: true },
            { text: 'utilizing machine learning and data engineering techniques such as, ', highlight: false },
            { text: 'data processing/cleaning, exploratory data analysis (EDA), statistical modeling, data visualization, model evaluation and optimization.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },     
            { text: 'Applied modern ', highlight: false },
            { text: 'software engineering practices and system design principles ', highlight: true },
            { text: 'to develop full-stack solutions, utilizing ', highlight: false },
            { text: 'version control and adhering to the software development lifecycle (SDLC).', highlight: true },
        ],
    },
];
