export const experienceData = [
    {
        fileName: 'Steris.txt',
        logo: 'steris_logo.svg',
        title: 'Software Integration Engineer',
        time: 'October 2025 - Present',
        description: [
            { text: 'Integrate, test, and deploy ', highlight: true },
            { text: 'enterprise healthcare software solutions ', highlight: false },
            { text: 'within hospital enterprise networks, ', highlight: true },
            { text: 'including configuring virtualized environments and consulting on complex IT architectures.', highlight: false },
            { text: '', break: true },
            { text: 'Manage full-lifecycle software integration projects, ', highlight: true },
            { text: 'collaborating directly with hospital IT teams, internal stakeholders, and third-party vendors to ensure ', highlight: false },
            { text: 'seamless data exchange and system interoperability.', highlight: true },
            { text: '', break: true },
            { text: 'Configure inbound clinical data pipelines, ', highlight: false },
            { text: 'processing HL7 SIU scheduling messages and DICOM C-FIND (MWL) queries ', highlight: true },
            { text: 'to route patient and surgical data to a ', highlight: false },
            { text: 'PostgreSQL database ', highlight: true },
            { text: 'and downstream OR devices.', highlight: false },
            { text: '', break: true },
            { text: 'Orchestrate outbound clinical export pipelines, ensuring captured OR media is archived to a central server and routed via ', highlight: false },
            { text: 'enterprise NAS dropoffs, HL7 ORU messages to EMRs, or DICOM C-STORE to PACS.', highlight: true },
            { text: '', break: true },
            { text: 'Manage high-stakes EMR cutovers and system go-lives, ', highlight: true },
            { text: 'providing continuous monitoring and ', highlight: false },
            { text: 'Tier-3 technical support ', highlight: true },
            { text: 'across multiple customer facilities to ensure zero disruption to clinical operations.', highlight: false },
            { text: '', break: true },
            { text: 'Design and develop RESTful APIs ', highlight: true },
            { text: 'for OR medical devices, integrating hardware endpoints into the core application to enable ', highlight: false },
            { text: 'seamless, centralized remote device management.', highlight: true },
            { text: '', break: true },
            { text: 'Engineer internal tools using ', highlight: true },
            { text: 'Ruby and Ansible ', highlight: false },
            { text: 'to automate application OVA customer configurations ', highlight: true },
            { text: 'and OR medical device provisioning, ', highlight: false },
            { text: 'reducing manual setup times by 70%.', highlight: true },
        ]
    },
    {
        fileName: 'East_End_Hand_Surgery.txt',
        logo: 'eehs_logo.svg',
        title: 'Software Application Analyst & Programmer',
        time: 'May 2016 - October 2025',
        description: [
            { text: 'Design, build, implement, test and modify custom ', highlight: true },
            { text: 'graphical user interfaces (GUIs) written in Python that seamlessly integrate with EMR systems ', highlight: false },
            { text: 'to automate healthcare workflows, ', highlight: false },
            { text: 'saving end-users 14+ hours weekly.', highlight: true },
            { text: '', break: true },
            { text: 'Translate ', highlight: true },
            { text: 'business requirements into ', highlight: false },
            { text: 'technical solutions, ', highlight: true },
            { text: 'identifying and implementing existing software where possible, and ', highlight: false },
            { text: 'developing custom applications for specific niche problems.', highlight: true },
            { text: '', break: true },
            { text: 'Serve as the primary ', highlight: false },
            { text: 'Application Analyst and EMR Administrator, ', highlight: true },
            { text: 'overseeing all ', highlight: false },
            { text: 'application configurations, workflow optimization, and user access control ', highlight: true },
            { text: 'to ensure seamless clinical and business operations.', highlight: false },
            { text: '', break: true },
            { text: 'Create and manage comprehensive documentation ', highlight: true },
            { text: 'for custom Python applications and EMR system configurations, and ', highlight: false },
            { text: 'provide training ', highlight: true },
            { text: 'to ensure end-user proficiency and streamlined workflows.', highlight: false },
            { text: '', break: true },
            { text: 'Manage multiple simultaneous application projects ', highlight: true },
            { text: 'throughout the ', highlight: false },
            { text: 'Software Development Lifecycle (SDLC),', highlight: true },
            { text: 'including application development/integration, system upgrades, and data migration initiatives, ', highlight: false },
            { text: 'effectively prioritizing work assignments to meet critical deadlines.', highlight: true },
            { text: '', break: true },
            { text: 'Act as the key liaison ', highlight: true },
            { text: 'for clinical staff, the EMR provider and third-party vendors, ', highlight: false },
            { text: 'proactively troubleshooting issues, coordinating system updates, and championing new features ', highlight: true },
            { text: 'that directly improve operational efficiency.', highlight: false },
            { text: '', break: true },
            { text: 'Manage 2+ TB ', highlight: true },
            { text: 'of sensitive patient records, ensuring ', highlight: false },
            { text: 'data integrity, security, and adherence to HIPAA compliance ', highlight: true },
            { text: 'through robust backup protocols and data management best practices.', highlight: false },
            { text: '', break: true },
            { text: "Led the successful ", highlight: true },
            { text: "reorganization and modernization of the company's digital file structure, including the migration to an optimized, centralized storage solution, which ", highlight: false },
            { text: 'reduced data storage and retrieval time by 50% and directly contributed to increased productivity.', highlight: true }
        ]
    },
    {
        fileName: 'Data_Annotation_Tech.txt',
        logo: 'DA_logo.svg',
        title: 'ML Specialist - LLM Training & Debugging',
        time: 'April 2024 - October 2025',
        description: [
            { text: 'Apply', highlight: false },
            { text: ' Reinforcement Learning from Human Feedback (RLHF)', highlight: true },
            { text: ' to enhance the', highlight: false },
            { text: ' efficiency and adaptability', highlight: true },
            { text: ' of machine learning models.', highlight: false },
            { text: '', break: true },
            { text: 'Debug and optimize code', highlight: true },
            { text: ' ensuring compliance with ethical and legal standards in ', highlight: false },
            { text: ' data-sensitive environments.', highlight: true },
            { text: '', break: true },
            { text: 'Leverage', highlight: false },
            { text: ' prompt engineering techniques', highlight: true },
            { text: ' to evaluate and improve model performance.', highlight: false },
        ]
    },
    {
        fileName: 'CUNY_Tech_Prep.txt',
        logo: 'CTP_logo.png',
        title: 'Data Science & Software Engineer Fellow',
        time: 'July 2024 - May 2025',
        description: [
            { text: 'Selected for a ', highlight: false },
            { text: 'highly competitive year-long fellowship ', highlight: true },
            { text: 'utilizing machine learning and data engineering techniques such as, ', highlight: false },
            { text: 'data processing/cleaning, exploratory data analysis (EDA), statistical modeling, data visualization, model evaluation and optimization.', highlight: true },
            { text: '', break: true },
            { text: 'Applied modern ', highlight: false },
            { text: 'software engineering practices and system design principles ', highlight: true },
            { text: 'to develop full-stack solutions, utilizing ', highlight: false },
            { text: 'version control and adhering to the software development lifecycle (SDLC).', highlight: true },
        ],
    },
];
