export const experienceData = [
    {
        fileName: 'East_End_Hand_Surgery.txt',
        title: 'Software Application Developer/Analyst',
        time: 'May 2016 - Present',
        description: [
            { text: 'Develop, test, deploy and maintain custom ', highlight: false },
            { text: 'Python software applications that seamlessly integrate with EMR systems, ', highlight: true },
            { text: 'streamlining healthcare workflows ', highlight: true },
            { text: '(e.g. patient schedule creation, intake distribution, billing, secure file encryption) and significantly improving operational efficiency by saving clinical staff ', highlight: false },
            { text: '8+ hours weekly.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Manage ', highlight: false },
            { text: 'comprehensive documentation ', highlight: true },
            { text: 'for custom Python applications and EMR system configurations.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Act as the EMR administrator and analyst, overseeing ', highlight: false },
            { text: 'system configuration, configuring builds, optimizing performance, managing user access, and troubleshooting ', highlight: true },
            { text: 'to ensure seamless clinical operations.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Manage critical vendor relationships, serving as the ', highlight: false },
            { text: 'primary point of contact for the EMR provider to troubleshoot issues, coordinate updates, and advocate for system improvements.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Manage ', highlight: false },
            { text: '2+ TB ', highlight: true },
            { text: 'of sensitive patient records, ensuring ', highlight: false },
            { text: 'data integrity, security, and adherence to HIPAA compliance ', highlight: true },
            { text: 'through robust backup protocols and data management best practices.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: "Led the successful reorganization of the company's file structure, significantly improving data retrieval and storage efficiency by ", highlight: false },
            { text: '2x and directly contributing to increased clinical productivity.', highlight: true }
        ]
    },
    {
        fileName: 'Data_Annotation_Tech.txt',
        title: 'ML Specialist - LLM Training & Debugging',
        time: 'April 2024 - Present',
        description: [
            { text: 'Apply', highlight: false },
            { text: ' Reinforcement Learning from Human Feedback (RLHF)', highlight: true },
            { text: ' to enhance the', highlight: false },
            { text: ' efficiency and adaptability', highlight: true },
            { text: ' of machine learning models.', highlight: false },
            { text: '', break: true },
            { text: '', break: true },
            { text: 'Debug and optimize code', highlight: true },
            { text: ' ensuring compliance with ethical and legal standards in ', highlight: false },
            { text: ' data-sensitive environments.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },            
            { text: 'Leverage', highlight: false },
            { text: ' prompt engineering techniques', highlight: true },
            { text: ' to evaluate and improve model performance.', highlight: false },
        ]
    },    
    {
        fileName: 'CUNY_Tech_Prep.txt',
        title: 'Data Science & Software Engineer Fellow',
        time: 'July 2024 - May 2025',
        description: [
            { text: 'Selected for a ', highlight: false },
            { text: 'highly competitive year-long fellowship ', highlight: true },
            { text: 'utilizing machine learning and data engineering techniques such as, ', highlight: false },
            { text: 'data processing/cleaning, exploratory data analysis (EDA), statistical modeling, data visualization, model evaluation and optimization.', highlight: true },
            { text: '', break: true },
            { text: '', break: true },     
            { text: 'Applied modern ', highlight: false },
            { text: 'software engineering practices and system design principles ', highlight: true },
            { text: 'to develop full-stack solutions, utilizing ', highlight: false },
            { text: 'version control and adhering to the software development lifecycle (SDLC).', highlight: true },
        ],
    },
];
